/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.repository.ClienteRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.PerfilRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.UsuarioRepository;
import br.com.ifba.projetogerenciadorsenhas.domain.Usuario;
import br.com.ifba.projetogerenciadorsenhas.domain.Perfil;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricio
 */
public class CadastroAtendente1 extends javax.swing.JFrame {

    private final ClienteRepository clienteRepository;
    private final PerfilRepository perfilRepository;
    private final UsuarioRepository usuarioRepository;
    private Object perfilSelecionado;

    public CadastroAtendente1(ClienteRepository clienteRepository, PerfilRepository perfilRepository, UsuarioRepository usuarioRepository) {
        this.clienteRepository = clienteRepository;
        this.perfilRepository = perfilRepository;
        this.usuarioRepository = usuarioRepository;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroAtendente = new javax.swing.JPanel();
        txtTextoCadastro = new javax.swing.JLabel();
        lblTextoNovoAtendente = new javax.swing.JLabel();
        pnlInformaçõesAtendente = new javax.swing.JPanel();
        lblInformaçõesPessoais = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtAcesso = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblPerfil = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        lblGuiche = new javax.swing.JLabel();
        cbmGuiche = new javax.swing.JComboBox<>();
        btnSavar = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCadastroAtendente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastroAtendente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));

        txtTextoCadastro.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtTextoCadastro.setText("Cadastro de Atendente");

        lblTextoNovoAtendente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoNovoAtendente.setText("Módulo Cadastro - Novo Atendente");

        pnlInformaçõesAtendente.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformaçõesAtendente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlInformaçõesAtendente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInformaçõesPessoais.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblInformaçõesPessoais.setText("Informações Pessoais");
        pnlInformaçõesAtendente.add(lblInformaçõesPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 26));
        pnlInformaçõesAtendente.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 40));

        lblNome.setText("Nome Completo");
        pnlInformaçõesAtendente.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 119, 28));

        lblCPF.setText("CPF");
        pnlInformaçõesAtendente.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        pnlInformaçõesAtendente.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 40));

        txtAcesso.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAcesso.setText("Acesso Sistema");
        pnlInformaçõesAtendente.add(txtAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        lblLogin.setText("Usuario");
        pnlInformaçõesAtendente.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
        pnlInformaçõesAtendente.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 390, 40));

        lblSenha.setText("Senha");
        pnlInformaçõesAtendente.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));
        pnlInformaçõesAtendente.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 390, 40));

        lblPerfil.setText("Perfil");
        pnlInformaçõesAtendente.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - ADMINISTRADOR", "2 - ATENDENTE ", "3 - GUICHÊS" }));
        cmbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilActionPerformed(evt);
            }
        });
        pnlInformaçõesAtendente.add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 200, 30));

        lblGuiche.setText("Guiche");
        pnlInformaçõesAtendente.add(lblGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        cbmGuiche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guiche 1 - FINANCEIRO.", "Guiche 2 - SOCIAL.", "Guiche 3 - DOCUMENTAÇÃO.", "Guiche 4 - TÂNSITO", "Guiche 5 - TRABALHO.", "Guiche 6 - PREVIDÊNCIA.", " " }));
        cbmGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmGuicheActionPerformed(evt);
            }
        });
        pnlInformaçõesAtendente.add(cbmGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 200, 30));

        btnSavar.setBackground(new java.awt.Color(255, 0, 51));
        btnSavar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnSavar.setForeground(new java.awt.Color(255, 255, 255));
        btnSavar.setText("Salvar");
        btnSavar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavarActionPerformed(evt);
            }
        });
        pnlInformaçõesAtendente.add(btnSavar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 40));

        btnCancela.setBackground(new java.awt.Color(255, 0, 51));
        btnCancela.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCancela.setForeground(new java.awt.Color(255, 255, 255));
        btnCancela.setText("Cancela");
        pnlInformaçõesAtendente.add(btnCancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 160, 40));

        javax.swing.GroupLayout pnlCadastroAtendenteLayout = new javax.swing.GroupLayout(pnlCadastroAtendente);
        pnlCadastroAtendente.setLayout(pnlCadastroAtendenteLayout);
        pnlCadastroAtendenteLayout.setHorizontalGroup(
            pnlCadastroAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAtendenteLayout.createSequentialGroup()
                .addGroup(pnlCadastroAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroAtendenteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlCadastroAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextoNovoAtendente)
                            .addComponent(pnlInformaçõesAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCadastroAtendenteLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(txtTextoCadastro)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlCadastroAtendenteLayout.setVerticalGroup(
            pnlCadastroAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroAtendenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTextoCadastro)
                .addGap(36, 36, 36)
                .addComponent(lblTextoNovoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInformaçõesAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilActionPerformed

    private void cbmGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmGuicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmGuicheActionPerformed

    private void btnSavarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavarActionPerformed
        String nomeStr = txtNome.getText() != null ? txtNome.getText().trim() : "";
        String usuarioLogin = txtUsuario.getText() != null ? txtUsuario.getText().trim() : ""; 
        String senhaStr = txtSenha.getText() != null ? txtSenha.getText().trim() : "";

        Object itemSelecionado = cmbPerfil.getSelectedItem();
        if(itemSelecionado == null || nomeStr.isEmpty() || usuarioLogin.isEmpty() || senhaStr.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }

        String perfilSelecionado = itemSelecionado.toString();

        try{
            String[] partes = perfilSelecionado.split(" - ");
            Long idPerfil = Long.parseLong(partes[0].trim()); 

            Optional<Perfil> perfilOptional = perfilRepository.findById(idPerfil);

            if(perfilOptional.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Erro: Perfil com ID " + idPerfil + " não encontrado!");
                return;
            }

            Usuario novoUsuario = new Usuario();
            novoUsuario.setLogin(usuarioLogin); 
            novoUsuario.setSenha(senhaStr); 
            novoUsuario.setPerfil(perfilOptional.get());

            usuarioRepository.save(novoUsuario);

            javax.swing.JOptionPane.showMessageDialog(this, "Atendente cadastrado com sucesso!");
            this.dispose(); 

        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao processar o ID do perfil: " + e.getMessage());
        }catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSavarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSavar;
    private javax.swing.JComboBox<String> cbmGuiche;
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblInformaçõesPessoais;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTextoNovoAtendente;
    private javax.swing.JPanel pnlCadastroAtendente;
    private javax.swing.JPanel pnlInformaçõesAtendente;
    private javax.swing.JLabel txtAcesso;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JLabel txtTextoCadastro;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
