/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

/**
 *
 * @author fabricio
 */
public class ExcluirAtendente extends javax.swing.JPanel {

    /**
     * Creates new form ExcluirAtendente
     */
    public ExcluirAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlExcuirAtendente = new javax.swing.JPanel();
        txtExcluirAtendente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNomeaExculir = new javax.swing.JLabel();
        pnlNomeaExcluir = new javax.swing.JPanel();
        lblExcluir = new javax.swing.JLabel();
        txtPesquisanomeAtendente = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        pnlNomeAtendente = new javax.swing.JPanel();
        lblNomeAtendente = new javax.swing.JLabel();
        pnlCPFatendente = new javax.swing.JPanel();
        lblCpfAtendente = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblGuiche = new javax.swing.JLabel();
        pnlPerfil = new javax.swing.JPanel();
        lblPerfill = new javax.swing.JLabel();
        pnlGuiche = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pnlUsuario = new javax.swing.JPanel();
        lblUsuarioExcluindo = new javax.swing.JLabel();
        pnlSenha = new javax.swing.JPanel();
        lblSenhaatendente = new javax.swing.JLabel();
        btnExcluiAtendente = new javax.swing.JButton();
        lblTextoExcluirAtendente = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        pnlExcuirAtendente.setBackground(new java.awt.Color(255, 255, 255));
        pnlExcuirAtendente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        txtExcluirAtendente.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtExcluirAtendente.setText("Excluir Atendente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNomeaExculir.setText("Nome do atendente");

        pnlNomeaExcluir.setBackground(new java.awt.Color(255, 255, 255));
        pnlNomeaExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ExcluirAtendente/lupao(1).png"))); // NOI18N

        txtPesquisanomeAtendente.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisanomeAtendente.setText("Pesquisa");

        javax.swing.GroupLayout pnlNomeaExcluirLayout = new javax.swing.GroupLayout(pnlNomeaExcluir);
        pnlNomeaExcluir.setLayout(pnlNomeaExcluirLayout);
        pnlNomeaExcluirLayout.setHorizontalGroup(
            pnlNomeaExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeaExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisanomeAtendente)
                .addContainerGap())
        );
        pnlNomeaExcluirLayout.setVerticalGroup(
            pnlNomeaExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeaExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNomeaExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisanomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNome.setText("Nome");

        lblCPF.setText("CPF");

        pnlNomeAtendente.setBackground(new java.awt.Color(255, 255, 255));
        pnlNomeAtendente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lblNomeAtendente.setText("Nome");

        javax.swing.GroupLayout pnlNomeAtendenteLayout = new javax.swing.GroupLayout(pnlNomeAtendente);
        pnlNomeAtendente.setLayout(pnlNomeAtendenteLayout);
        pnlNomeAtendenteLayout.setHorizontalGroup(
            pnlNomeAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeAtendenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNomeAtendenteLayout.setVerticalGroup(
            pnlNomeAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNomeAtendenteLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblNomeAtendente)
                .addContainerGap())
        );

        pnlCPFatendente.setBackground(new java.awt.Color(255, 255, 255));
        pnlCPFatendente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lblCpfAtendente.setText("CPF");

        javax.swing.GroupLayout pnlCPFatendenteLayout = new javax.swing.GroupLayout(pnlCPFatendente);
        pnlCPFatendente.setLayout(pnlCPFatendenteLayout);
        pnlCPFatendenteLayout.setHorizontalGroup(
            pnlCPFatendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFatendenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCpfAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCPFatendenteLayout.setVerticalGroup(
            pnlCPFatendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCPFatendenteLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblCpfAtendente)
                .addContainerGap())
        );

        lblPerfil.setText("Perfil");

        lblGuiche.setText("Guiche");

        pnlPerfil.setBackground(new java.awt.Color(255, 255, 255));
        pnlPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lblPerfill.setText("Perfil");

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPerfill)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPerfill, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlGuiche.setBackground(new java.awt.Color(255, 255, 255));
        pnlGuiche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        javax.swing.GroupLayout pnlGuicheLayout = new javax.swing.GroupLayout(pnlGuiche);
        pnlGuiche.setLayout(pnlGuicheLayout);
        pnlGuicheLayout.setHorizontalGroup(
            pnlGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        pnlGuicheLayout.setVerticalGroup(
            pnlGuicheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        lblLogin.setText("Usuario");

        lblSenha.setText("Senha");

        pnlUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lblUsuarioExcluindo.setText("Nome de Usuario");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioExcluindo)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioExcluindo)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        lblSenhaatendente.setText("Senha");

        javax.swing.GroupLayout pnlSenhaLayout = new javax.swing.GroupLayout(pnlSenha);
        pnlSenha.setLayout(pnlSenhaLayout);
        pnlSenhaLayout.setHorizontalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhaatendente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSenhaLayout.setVerticalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhaatendente)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnExcluiAtendente.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluiAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ExcluirAtendente/deletar-usuario.png"))); // NOI18N
        btnExcluiAtendente.setText("Excluir Atendente");
        btnExcluiAtendente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPerfil)
                    .addComponent(lblNomeaExculir)
                    .addComponent(pnlNomeaExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF)
                            .addComponent(pnlNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlCPFatendente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblGuiche)
                            .addComponent(pnlGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSenha)
                                    .addComponent(lblLogin)
                                    .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluiAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblNomeaExculir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNomeaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCPF)
                                    .addComponent(lblSenha)))
                            .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCPFatendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGuiche))
                    .addComponent(btnExcluiAtendente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lblTextoExcluirAtendente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTextoExcluirAtendente.setText("Módulo Exclusão - Excluir Atendente");

        javax.swing.GroupLayout pnlExcuirAtendenteLayout = new javax.swing.GroupLayout(pnlExcuirAtendente);
        pnlExcuirAtendente.setLayout(pnlExcuirAtendenteLayout);
        pnlExcuirAtendenteLayout.setHorizontalGroup(
            pnlExcuirAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExcuirAtendenteLayout.createSequentialGroup()
                .addGroup(pnlExcuirAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExcuirAtendenteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlExcuirAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextoExcluirAtendente)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlExcuirAtendenteLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(txtExcluirAtendente)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlExcuirAtendenteLayout.setVerticalGroup(
            pnlExcuirAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExcuirAtendenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtExcluirAtendente)
                .addGap(32, 32, 32)
                .addComponent(lblTextoExcluirAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExcuirAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExcuirAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 576, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluiAtendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCpfAtendente;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblGuiche;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeAtendente;
    private javax.swing.JLabel lblNomeaExculir;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPerfill;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaatendente;
    private javax.swing.JLabel lblTextoExcluirAtendente;
    private javax.swing.JLabel lblUsuarioExcluindo;
    private javax.swing.JPanel pnlCPFatendente;
    private javax.swing.JPanel pnlExcuirAtendente;
    private javax.swing.JPanel pnlGuiche;
    private javax.swing.JPanel pnlNomeAtendente;
    private javax.swing.JPanel pnlNomeaExcluir;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlSenha;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JLabel txtExcluirAtendente;
    private javax.swing.JTextField txtPesquisanomeAtendente;
    // End of variables declaration//GEN-END:variables
}
