/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.repository.*;
import br.com.ifba.projetogerenciadorsenhas.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
/**
 *
 * @author fabricio
 */
@Component
public class MenuPrincipal extends javax.swing.JFrame {

    private final ClienteRepository clienteRepository;
    private final PerfilRepository perfilRepository;
    private final UsuarioRepository usuarioRepository;
    private final UsuarioService usuarioService;
    private final SenhaRepository senhaRepository;
    private final SenhaService senhaService;

    @Autowired
    public MenuPrincipal(ClienteRepository clienteRepository, PerfilRepository perfilRepository, 
                         UsuarioRepository usuarioRepository, UsuarioService usuarioService, 
                         SenhaRepository senhaRepository, SenhaService senhaService) {
        this.clienteRepository = clienteRepository;
        this.perfilRepository = perfilRepository;
        this.usuarioRepository = usuarioRepository;
        this.usuarioService = usuarioService;
        this.senhaRepository = senhaRepository;
        this.senhaService = senhaService;
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(br.com.ifba.projetogerenciadorsenhas.repository.ClienteRepository clienteRepository) {
        initComponents();
        this.clienteRepository = clienteRepository;
        this.perfilRepository = null;
        this.usuarioRepository = null;
        this.usuarioService = null;
        this.senhaRepository = null;
        this.senhaService = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelamenuPricinpal = new javax.swing.JPanel();
        btnNovoAtendimento = new javax.swing.JButton();
        bntPainelGuiche = new javax.swing.JButton();
        btnPainelTV = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTelamenuPricinpal.setBackground(new java.awt.Color(0, 204, 204));
        pnlTelamenuPricinpal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTelamenuPricinpal.setForeground(new java.awt.Color(153, 153, 153));
        pnlTelamenuPricinpal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNovoAtendimento.setBackground(new java.awt.Color(102, 255, 102));
        btnNovoAtendimento.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        btnNovoAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/adicionar(1).png"))); // NOI18N
        btnNovoAtendimento.setText("Novo Atendimento");
        btnNovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAtendimentoActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(btnNovoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 100));

        bntPainelGuiche.setBackground(new java.awt.Color(0, 102, 255));
        bntPainelGuiche.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        bntPainelGuiche.setForeground(new java.awt.Color(255, 255, 255));
        bntPainelGuiche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/relatorio-de-noticias.png"))); // NOI18N
        bntPainelGuiche.setText("Painel do Guichê");
        bntPainelGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPainelGuicheActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(bntPainelGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 240, 100));

        btnPainelTV.setBackground(new java.awt.Color(255, 153, 51));
        btnPainelTV.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        btnPainelTV.setForeground(new java.awt.Color(255, 255, 255));
        btnPainelTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tela-de-tv.png"))); // NOI18N
        btnPainelTV.setText("Painel de TV");
        btnPainelTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainelTVActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(btnPainelTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 240, 100));

        btnRelatorios.setBackground(new java.awt.Color(255, 51, 51));
        btnRelatorios.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/relatorio.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        pnlTelamenuPricinpal.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 240, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador de Senhas  ");
        pnlTelamenuPricinpal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 430, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTelamenuPricinpal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 810, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelamenuPricinpal, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelamenuPricinpal, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPainelGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPainelGuicheActionPerformed
        // TODO add your handling code here:
        TelaguicheFinaceiro telaGuiche = new TelaguicheFinaceiro(this.senhaService, this.senhaRepository);
        telaGuiche.setVisible(true);
    }//GEN-LAST:event_bntPainelGuicheActionPerformed

    private void btnNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAtendimentoActionPerformed
        // TODO add your handling code here:
        TelaAtendente1 tela = new TelaAtendente1(this.clienteRepository, this.perfilRepository, this.usuarioService, this.senhaRepository);
        tela.setVisible(true);
    }//GEN-LAST:event_btnNovoAtendimentoActionPerformed

    private void btnPainelTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainelTVActionPerformed
        // TODO add your handling code here:
        PainelChamanda tela = new PainelChamanda(this.senhaRepository);
        tela.setVisible(true);
    }//GEN-LAST:event_btnPainelTVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPainelGuiche;
    private javax.swing.JButton btnNovoAtendimento;
    private javax.swing.JButton btnPainelTV;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlTelamenuPricinpal;
    // End of variables declaration//GEN-END:variables
}
