/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.repository.*;
import br.com.ifba.projetogerenciadorsenhas.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
/**
 *
 * @author fabricio
 */
@Component
public class MenuPrincipal extends javax.swing.JFrame {

    private final ClienteRepository clienteRepository;
    private final PerfilRepository perfilRepository;
    private final UsuarioRepository usuarioRepository;
    private final UsuarioService usuarioService;
    private final SenhaRepository senhaRepository;
    private final SenhaService senhaService;

    @Autowired
    public MenuPrincipal(ClienteRepository clienteRepository, PerfilRepository perfilRepository, 
                         UsuarioRepository usuarioRepository, UsuarioService usuarioService, 
                         SenhaRepository senhaRepository, SenhaService senhaService) {
        this.clienteRepository = clienteRepository;
        this.perfilRepository = perfilRepository;
        this.usuarioRepository = usuarioRepository;
        this.usuarioService = usuarioService;
        this.senhaRepository = senhaRepository;
        this.senhaService = senhaService;
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(br.com.ifba.projetogerenciadorsenhas.repository.ClienteRepository clienteRepository) {
        initComponents();
        this.clienteRepository = clienteRepository;
        this.perfilRepository = null;
        this.usuarioRepository = null;
        this.usuarioService = null;
        this.senhaRepository = null;
        this.senhaService = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelamenuPricinpal = new javax.swing.JPanel();
        pnlBarraLateral = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        btnAtendimento = new javax.swing.JButton();
        btnConfigurações = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnNovoAtendimento = new javax.swing.JButton();
        bntPainelGuiche = new javax.swing.JButton();
        btnPainelTV = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTelamenuPricinpal.setBackground(new java.awt.Color(255, 255, 255));
        pnlTelamenuPricinpal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraLateral.setBackground(new java.awt.Color(0, 204, 204));
        pnlBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastro.setText("Cadastro");
        pnlBarraLateral.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 178, 41));

        btnAtendimento.setText("Atendimento");
        pnlBarraLateral.add(btnAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 178, 41));

        btnConfigurações.setText("Configurações");
        pnlBarraLateral.add(btnConfigurações, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 40));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnlBarraLateral.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 40));

        pnlTelamenuPricinpal.add(pnlBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 430));

        btnNovoAtendimento.setBackground(new java.awt.Color(51, 204, 0));
        btnNovoAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAtendimento.setText("Novo Atendimento");
        btnNovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAtendimentoActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(btnNovoAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 160, 50));

        bntPainelGuiche.setBackground(new java.awt.Color(0, 102, 255));
        bntPainelGuiche.setForeground(new java.awt.Color(255, 255, 255));
        bntPainelGuiche.setText("Painel do Guichê");
        bntPainelGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPainelGuicheActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(bntPainelGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 160, 50));

        btnPainelTV.setBackground(new java.awt.Color(255, 153, 51));
        btnPainelTV.setForeground(new java.awt.Color(255, 255, 255));
        btnPainelTV.setText("Painel de TV");
        btnPainelTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainelTVActionPerformed(evt);
            }
        });
        pnlTelamenuPricinpal.add(btnPainelTV, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 170, 50));

        btnRelatorios.setBackground(new java.awt.Color(153, 153, 153));
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setText("Relatórios");
        pnlTelamenuPricinpal.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelamenuPricinpal, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelamenuPricinpal, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void bntPainelGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPainelGuicheActionPerformed
        // TODO add your handling code here:
        TelaguicheFinaceiro telaGuiche = new TelaguicheFinaceiro(this.senhaService, this.senhaRepository);
        telaGuiche.setVisible(true);
    }//GEN-LAST:event_bntPainelGuicheActionPerformed

    private void btnNovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAtendimentoActionPerformed
        // TODO add your handling code here:
        TelaAtendente1 tela = new TelaAtendente1(this.clienteRepository, this.perfilRepository, this.usuarioService, this.senhaRepository);
        tela.setVisible(true);
    }//GEN-LAST:event_btnNovoAtendimentoActionPerformed

    private void btnPainelTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainelTVActionPerformed
        // TODO add your handling code here:
        PainelChamanda tela = new PainelChamanda(this.senhaRepository);
        tela.setVisible(true);
    }//GEN-LAST:event_btnPainelTVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPainelGuiche;
    private javax.swing.JButton btnAtendimento;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnConfigurações;
    private javax.swing.JButton btnNovoAtendimento;
    private javax.swing.JButton btnPainelTV;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel pnlBarraLateral;
    private javax.swing.JPanel pnlTelamenuPricinpal;
    // End of variables declaration//GEN-END:variables
}
