/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.domain.Senha;
import br.com.ifba.projetogerenciadorsenhas.repository.SenhaRepository;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 *
 * @author fabricio
 */
@Component
public class PainelChamanda extends javax.swing.JFrame {

    private final SenhaRepository senhaRepository;

    public PainelChamanda(SenhaRepository senhaRepository) {
        this.senhaRepository = senhaRepository;
        initComponents();
        iniciarTimer();
        setLocationRelativeTo(null);
    }

    private void iniciarTimer() {
        javax.swing.Timer timer = new javax.swing.Timer(5000, e -> atualizarDados());
        timer.start();
    }

    private void atualizarDados() {
        List<Senha> emAtendimento = senhaRepository.findByStatus("EM_ATENDIMENTO");
        if (!emAtendimento.isEmpty()) {
            Senha atual = emAtendimento.get(emAtendimento.size() - 1);
            lblSenha.setText(atual.getCodigo());
            lblTipoAtendimento.setText("GUICHÊ: " + (atual.getGuicheResponsavel() != null ? atual.getGuicheResponsavel() : "---"));
        } else {
            lblSenha.setText("AGUARDANDO");
            lblTipoAtendimento.setText("---");
        }

        List<Senha> aguardando = senhaRepository.findByStatus("AGUARDANDO");
        preencherTabela(tblProximasSenhas, aguardando);

        List<Senha> finalizadas = senhaRepository.findByStatus("FINALIZADO");
        preencherTabela(tblUltimasSenhas, finalizadas);
    }
    
    private void preencherTabela(javax.swing.JTable tabela, List<Senha> senhas) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabela.getModel();
        model.setRowCount(0);
        for (Senha s : senhas) {
            model.addRow(new Object[]{s.getCodigo(), s.getGuicheResponsavel()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPainelChamanda = new javax.swing.JPanel();
        lblPainelChamadas = new javax.swing.JLabel();
        pnlSenhaAtual = new javax.swing.JPanel();
        lblSenhaAtual = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTipoAtendimento = new javax.swing.JLabel();
        pnlProximasSenhas = new javax.swing.JPanel();
        lblProximasSenhas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProximasSenhas = new javax.swing.JTable();
        pnlSenhaChamandas = new javax.swing.JPanel();
        lblUltimasSenhaas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUltimasSenhas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPainelChamanda.setBackground(new java.awt.Color(255, 255, 255));
        pnlPainelChamanda.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        pnlPainelChamanda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPainelChamadas.setBackground(new java.awt.Color(0, 153, 153));
        lblPainelChamadas.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblPainelChamadas.setForeground(new java.awt.Color(0, 153, 153));
        lblPainelChamadas.setText("PAINEL DE SENHAS");
        pnlPainelChamanda.add(lblPainelChamadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        pnlSenhaAtual.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenhaAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        lblSenhaAtual.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblSenhaAtual.setText("Senha Atual");

        lblSenha.setFont(new java.awt.Font("Liberation Sans", 0, 90)); // NOI18N
        lblSenha.setText("SENHA1234");

        lblTipoAtendimento.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTipoAtendimento.setText("GUICHÊ: 01 - FINANCEIRO");

        javax.swing.GroupLayout pnlSenhaAtualLayout = new javax.swing.GroupLayout(pnlSenhaAtual);
        pnlSenhaAtual.setLayout(pnlSenhaAtualLayout);
        pnlSenhaAtualLayout.setHorizontalGroup(
            pnlSenhaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaAtualLayout.createSequentialGroup()
                .addGroup(pnlSenhaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSenhaAtualLayout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(lblSenhaAtual))
                    .addGroup(pnlSenhaAtualLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSenhaAtualLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(lblTipoAtendimento)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        pnlSenhaAtualLayout.setVerticalGroup(
            pnlSenhaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaAtualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhaAtual)
                .addGap(42, 42, 42)
                .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblTipoAtendimento)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pnlPainelChamanda.add(pnlSenhaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 79, 850, -1));

        pnlProximasSenhas.setBackground(new java.awt.Color(255, 255, 255));
        pnlProximasSenhas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        lblProximasSenhas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblProximasSenhas.setText("Proximas Senhas");

        tblProximasSenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SENHA", "GUICHÊ"
            }
        ));
        jScrollPane1.setViewportView(tblProximasSenhas);

        javax.swing.GroupLayout pnlProximasSenhasLayout = new javax.swing.GroupLayout(pnlProximasSenhas);
        pnlProximasSenhas.setLayout(pnlProximasSenhasLayout);
        pnlProximasSenhasLayout.setHorizontalGroup(
            pnlProximasSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProximasSenhasLayout.createSequentialGroup()
                .addGroup(pnlProximasSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProximasSenhasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProximasSenhasLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblProximasSenhas)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlProximasSenhasLayout.setVerticalGroup(
            pnlProximasSenhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProximasSenhasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProximasSenhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlPainelChamanda.add(pnlProximasSenhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 410, 240));

        pnlSenhaChamandas.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenhaChamandas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        lblUltimasSenhaas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblUltimasSenhaas.setText("Ultimas Senhas");

        tblUltimasSenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SENHA", "GUICHÊ"
            }
        ));
        jScrollPane2.setViewportView(tblUltimasSenhas);

        javax.swing.GroupLayout pnlSenhaChamandasLayout = new javax.swing.GroupLayout(pnlSenhaChamandas);
        pnlSenhaChamandas.setLayout(pnlSenhaChamandasLayout);
        pnlSenhaChamandasLayout.setHorizontalGroup(
            pnlSenhaChamandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaChamandasLayout.createSequentialGroup()
                .addGroup(pnlSenhaChamandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSenhaChamandasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSenhaChamandasLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblUltimasSenhaas)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlSenhaChamandasLayout.setVerticalGroup(
            pnlSenhaChamandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaChamandasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUltimasSenhaas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlPainelChamanda.add(pnlSenhaChamandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 400, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPainelChamanda, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPainelChamanda, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPainelChamadas;
    private javax.swing.JLabel lblProximasSenhas;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblTipoAtendimento;
    private javax.swing.JLabel lblUltimasSenhaas;
    private javax.swing.JPanel pnlPainelChamanda;
    private javax.swing.JPanel pnlProximasSenhas;
    private javax.swing.JPanel pnlSenhaAtual;
    private javax.swing.JPanel pnlSenhaChamandas;
    private javax.swing.JTable tblProximasSenhas;
    private javax.swing.JTable tblUltimasSenhas;
    // End of variables declaration//GEN-END:variables
}
