/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.repository.ClienteRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.PerfilRepository;
import br.com.ifba.projetogerenciadorsenhas.service.UsuarioService;

/**
 *
 * @author fabricio
 */
public class TelaAtendente1 extends javax.swing.JFrame {

    private final ClienteRepository clienteRepository;
    private final PerfilRepository perfilRepository;

    /**
     * Creates new form TeleAtendente
     * @param clienteRepository
     */
    public TelaAtendente1(ClienteRepository clienteRepository, PerfilRepository perfilRepository) {
        this.clienteRepository = clienteRepository;
        this.perfilRepository = perfilRepository;
        initComponents();
        setLocationRelativeTo(null);
    }

    public TelaAtendente1() {
        this(null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComponetes = new javax.swing.JPanel();
        lblTextoSuperior = new javax.swing.JLabel();
        pnlInformaçõesUsuario = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCpfUsuario = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDescriação = new javax.swing.JLabel();
        pnlNomeUsuario = new javax.swing.JPanel();
        txtNomeUsuario = new javax.swing.JTextField();
        pnlDataNascimento = new javax.swing.JPanel();
        txtDataNascimento = new javax.swing.JTextField();
        pnlCpfUsuario = new javax.swing.JPanel();
        txtCpfUsuario = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        txtEmailUsuario = new javax.swing.JTextField();
        pnlTelefone = new javax.swing.JPanel();
        txtTelefoneUsuario = new javax.swing.JTextField();
        pnlCidadeUsuario = new javax.swing.JPanel();
        txtCidadeUsuario = new javax.swing.JTextField();
        pnlBairroUsuario = new javax.swing.JPanel();
        txtBairroUsuario = new javax.swing.JTextField();
        pnlNumeroResidencia = new javax.swing.JPanel();
        txtNumeroResidencia = new javax.swing.JTextField();
        pnlDescricao = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtAtendimentoPioritario = new javax.swing.JRadioButton();
        rbtAtendimentoNorma = new javax.swing.JRadioButton();
        lblOpcaoPioridade = new javax.swing.JLabel();
        pnlOpcoesAtendimento = new javax.swing.JPanel();
        cbmGuiche = new javax.swing.JComboBox<>();
        btnGerarsenhaPioritaria = new javax.swing.JButton();
        btnGerarSenha = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblConfiguraçõesAtendimento = new javax.swing.JLabel();
        pnlMenuAtendente = new javax.swing.JPanel();
        lblPainelAtendente1 = new javax.swing.JLabel();
        lblNumerosAtendimentos = new javax.swing.JLabel();
        lblAtendimentosTotal1 = new javax.swing.JLabel();
        lblAtendimentosPioridade1 = new javax.swing.JLabel();
        lblSenhasNormais1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlTotaldeAtendimentos = new javax.swing.JPanel();
        lblTotaldeAtendimentos = new javax.swing.JLabel();
        pnlSenhasnaoPioritarias2 = new javax.swing.JPanel();
        lblSenhasnaoPioritarias2 = new javax.swing.JLabel();
        pnlTotalPioridade = new javax.swing.JPanel();
        txtTotalPioridade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDadosTotais1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnSairtelaAtendente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlComponetes.setBackground(new java.awt.Color(255, 255, 255));
        pnlComponetes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoSuperior.setText("Módulo Recepção - Cadastro de Cliente para Atendimento");
        pnlComponetes.add(lblTextoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        pnlInformaçõesUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformaçõesUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlInformaçõesUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeUsuario.setText("Nome:");
        pnlInformaçõesUsuario.add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblCidade.setText("Cidade");
        pnlInformaçõesUsuario.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblBairro.setText("Bairro");
        pnlInformaçõesUsuario.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        lblNumero.setText("Numero");
        pnlInformaçõesUsuario.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, -1));

        lblCpfUsuario.setText("CPF");
        pnlInformaçõesUsuario.add(lblCpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblDataNascimento.setText("Data de Nascimento");
        pnlInformaçõesUsuario.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        lblTelefone.setText("Telefone");
        pnlInformaçõesUsuario.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        lblEmail.setText("Email");
        pnlInformaçõesUsuario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        lblDescriação.setText("Descrição");
        pnlInformaçõesUsuario.add(lblDescriação, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        pnlNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlNomeUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNomeUsuarioLayout = new javax.swing.GroupLayout(pnlNomeUsuario);
        pnlNomeUsuario.setLayout(pnlNomeUsuarioLayout);
        pnlNomeUsuarioLayout.setHorizontalGroup(
            pnlNomeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNomeUsuarioLayout.setVerticalGroup(
            pnlNomeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInformaçõesUsuario.add(pnlNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 40));

        pnlDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        pnlDataNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout pnlDataNascimentoLayout = new javax.swing.GroupLayout(pnlDataNascimento);
        pnlDataNascimento.setLayout(pnlDataNascimentoLayout);
        pnlDataNascimentoLayout.setHorizontalGroup(
            pnlDataNascimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNascimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDataNascimentoLayout.setVerticalGroup(
            pnlDataNascimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataNascimentoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlInformaçõesUsuario.add(pnlDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 330, 40));

        pnlCpfUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlCpfUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout pnlCpfUsuarioLayout = new javax.swing.GroupLayout(pnlCpfUsuario);
        pnlCpfUsuario.setLayout(pnlCpfUsuarioLayout);
        pnlCpfUsuarioLayout.setHorizontalGroup(
            pnlCpfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCpfUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCpfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCpfUsuarioLayout.setVerticalGroup(
            pnlCpfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCpfUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlInformaçõesUsuario.add(pnlCpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 40));

        pnlEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        txtEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmailUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlInformaçõesUsuario.add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 390, 40));

        pnlTelefone.setBackground(new java.awt.Color(255, 255, 255));
        pnlTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        txtTelefoneUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTelefoneLayout = new javax.swing.GroupLayout(pnlTelefone);
        pnlTelefone.setLayout(pnlTelefoneLayout);
        pnlTelefoneLayout.setHorizontalGroup(
            pnlTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTelefoneUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTelefoneLayout.setVerticalGroup(
            pnlTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelefoneLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtTelefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlInformaçõesUsuario.add(pnlTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 220, 40));

        pnlCidadeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlCidadeUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout pnlCidadeUsuarioLayout = new javax.swing.GroupLayout(pnlCidadeUsuario);
        pnlCidadeUsuario.setLayout(pnlCidadeUsuarioLayout);
        pnlCidadeUsuarioLayout.setHorizontalGroup(
            pnlCidadeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCidadeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCidadeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCidadeUsuarioLayout.setVerticalGroup(
            pnlCidadeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCidadeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlInformaçõesUsuario.add(pnlCidadeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 320, 40));

        pnlBairroUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlBairroUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout pnlBairroUsuarioLayout = new javax.swing.GroupLayout(pnlBairroUsuario);
        pnlBairroUsuario.setLayout(pnlBairroUsuarioLayout);
        pnlBairroUsuarioLayout.setHorizontalGroup(
            pnlBairroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBairroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBairroUsuarioLayout.setVerticalGroup(
            pnlBairroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBairroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlInformaçõesUsuario.add(pnlBairroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 410, 40));

        pnlNumeroResidencia.setBackground(new java.awt.Color(255, 255, 255));
        pnlNumeroResidencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout pnlNumeroResidenciaLayout = new javax.swing.GroupLayout(pnlNumeroResidencia);
        pnlNumeroResidencia.setLayout(pnlNumeroResidenciaLayout);
        pnlNumeroResidenciaLayout.setHorizontalGroup(
            pnlNumeroResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumeroResidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumeroResidencia, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNumeroResidenciaLayout.setVerticalGroup(
            pnlNumeroResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumeroResidenciaLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlInformaçõesUsuario.add(pnlNumeroResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 130, 40));

        pnlDescricao.setBackground(new java.awt.Color(255, 255, 255));
        pnlDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        javax.swing.GroupLayout pnlDescricaoLayout = new javax.swing.GroupLayout(pnlDescricao);
        pnlDescricao.setLayout(pnlDescricaoLayout);
        pnlDescricaoLayout.setHorizontalGroup(
            pnlDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDescricaoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDescricaoLayout.setVerticalGroup(
            pnlDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlInformaçõesUsuario.add(pnlDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 470, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        rbtAtendimentoPioritario.setBackground(new java.awt.Color(255, 255, 255));
        rbtAtendimentoPioritario.setText("Usuário com necessidade de atendimento prioritário");

        rbtAtendimentoNorma.setBackground(new java.awt.Color(255, 255, 255));
        rbtAtendimentoNorma.setText("Usuário sem necessidade de atendimento prioritário");
        rbtAtendimentoNorma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAtendimentoNormaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtAtendimentoNorma, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(rbtAtendimentoPioritario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(rbtAtendimentoNorma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtAtendimentoPioritario)
                .addGap(12, 12, 12))
        );

        pnlInformaçõesUsuario.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 420, 80));

        lblOpcaoPioridade.setText("Opção de Prioridade");
        pnlInformaçõesUsuario.add(lblOpcaoPioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        pnlComponetes.add(pnlInformaçõesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 950, 390));

        pnlOpcoesAtendimento.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpcoesAtendimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbmGuiche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guiche 1 - FINANCEIRO E REGULAÇÃO FISCAL.", "Guiche 2 - SOCIAL.", "Guiche 3 - DOCUMENTAÇÃO E INDENTIFICAÇÃO.", "Guiche 4 - TÂNSITO E VEICULOS.", "Guiche 5 - TRABALHO E RENDA.", "Guiche 6 - SAÚDE E PREVIDÊNCIA.", " " }));
        cbmGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmGuicheActionPerformed(evt);
            }
        });

        btnGerarsenhaPioritaria.setBackground(new java.awt.Color(255, 255, 204));
        btnGerarsenhaPioritaria.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnGerarsenhaPioritaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/TelaAtendente/velho.png"))); // NOI18N
        btnGerarsenhaPioritaria.setText("Senha Prioritaria");
        btnGerarsenhaPioritaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));

        javax.swing.GroupLayout pnlOpcoesAtendimentoLayout = new javax.swing.GroupLayout(pnlOpcoesAtendimento);
        pnlOpcoesAtendimento.setLayout(pnlOpcoesAtendimentoLayout);
        pnlOpcoesAtendimentoLayout.setHorizontalGroup(
            pnlOpcoesAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesAtendimentoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbmGuiche, 0, 370, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnGerarsenhaPioritaria, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlOpcoesAtendimentoLayout.setVerticalGroup(
            pnlOpcoesAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcoesAtendimentoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlOpcoesAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarsenhaPioritaria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnlComponetes.add(pnlOpcoesAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 660, 150));

        btnGerarSenha.setBackground(new java.awt.Color(153, 255, 153));
        btnGerarSenha.setText("Gerar Senha");
        btnGerarSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        btnGerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSenhaActionPerformed(evt);
            }
        });
        pnlComponetes.add(btnGerarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 270, 70));

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pnlComponetes.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 270, 70));

        lblConfiguraçõesAtendimento.setText("Configurações de Atendimento");
        pnlComponetes.add(lblConfiguraçõesAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        pnlMenuAtendente.setBackground(new java.awt.Color(0, 153, 153));
        pnlMenuAtendente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMenuAtendente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPainelAtendente1.setBackground(new java.awt.Color(0, 153, 153));
        lblPainelAtendente1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblPainelAtendente1.setForeground(new java.awt.Color(255, 255, 255));
        lblPainelAtendente1.setText("Painel do Atendente");
        pnlMenuAtendente.add(lblPainelAtendente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblNumerosAtendimentos.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        lblNumerosAtendimentos.setForeground(new java.awt.Color(255, 255, 255));
        lblNumerosAtendimentos.setText("Atendimentos do dia");
        pnlMenuAtendente.add(lblNumerosAtendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblAtendimentosTotal1.setBackground(new java.awt.Color(255, 255, 255));
        lblAtendimentosTotal1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblAtendimentosTotal1.setForeground(new java.awt.Color(255, 255, 255));
        lblAtendimentosTotal1.setText("Total");
        pnlMenuAtendente.add(lblAtendimentosTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblAtendimentosPioridade1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblAtendimentosPioridade1.setForeground(new java.awt.Color(255, 255, 255));
        lblAtendimentosPioridade1.setText("Prioridade");
        pnlMenuAtendente.add(lblAtendimentosPioridade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 311, -1, -1));

        lblSenhasNormais1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblSenhasNormais1.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhasNormais1.setText("Senhas não Prioritaria");
        pnlMenuAtendente.add(lblSenhasNormais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, -1, -1));
        pnlMenuAtendente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, 250, 10));

        pnlTotaldeAtendimentos.setBackground(new java.awt.Color(0, 153, 153));
        pnlTotaldeAtendimentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblTotaldeAtendimentos.setBackground(new java.awt.Color(255, 255, 255));
        lblTotaldeAtendimentos.setForeground(new java.awt.Color(255, 255, 255));
        lblTotaldeAtendimentos.setText("0");

        javax.swing.GroupLayout pnlTotaldeAtendimentosLayout = new javax.swing.GroupLayout(pnlTotaldeAtendimentos);
        pnlTotaldeAtendimentos.setLayout(pnlTotaldeAtendimentosLayout);
        pnlTotaldeAtendimentosLayout.setHorizontalGroup(
            pnlTotaldeAtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotaldeAtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotaldeAtendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTotaldeAtendimentosLayout.setVerticalGroup(
            pnlTotaldeAtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotaldeAtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotaldeAtendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenuAtendente.add(pnlTotaldeAtendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 188, 250, -1));

        pnlSenhasnaoPioritarias2.setBackground(new java.awt.Color(0, 153, 153));
        pnlSenhasnaoPioritarias2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblSenhasnaoPioritarias2.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhasnaoPioritarias2.setText("0");

        javax.swing.GroupLayout pnlSenhasnaoPioritarias2Layout = new javax.swing.GroupLayout(pnlSenhasnaoPioritarias2);
        pnlSenhasnaoPioritarias2.setLayout(pnlSenhasnaoPioritarias2Layout);
        pnlSenhasnaoPioritarias2Layout.setHorizontalGroup(
            pnlSenhasnaoPioritarias2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhasnaoPioritarias2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhasnaoPioritarias2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSenhasnaoPioritarias2Layout.setVerticalGroup(
            pnlSenhasnaoPioritarias2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhasnaoPioritarias2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhasnaoPioritarias2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenuAtendente.add(pnlSenhasnaoPioritarias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 40));

        pnlTotalPioridade.setBackground(new java.awt.Color(0, 153, 153));
        pnlTotalPioridade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtTotalPioridade.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalPioridade.setText("0");

        javax.swing.GroupLayout pnlTotalPioridadeLayout = new javax.swing.GroupLayout(pnlTotalPioridade);
        pnlTotalPioridade.setLayout(pnlTotalPioridadeLayout);
        pnlTotalPioridadeLayout.setHorizontalGroup(
            pnlTotalPioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPioridadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalPioridade, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTotalPioridadeLayout.setVerticalGroup(
            pnlTotalPioridadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalPioridadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTotalPioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuAtendente.add(pnlTotalPioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 250, 40));

        tblDadosTotais1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Diario", "Semanal", "Mensal", "Anual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDadosTotais1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDadosTotais1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tblDadosTotais1);

        pnlMenuAtendente.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 270, 120));
        pnlMenuAtendente.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 250, -1));

        btnSairtelaAtendente.setText("Sair");
        btnSairtelaAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairtelaAtendenteActionPerformed(evt);
            }
        });
        pnlMenuAtendente.add(btnSairtelaAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 610, 140, 40));

        pnlComponetes.add(pnlMenuAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComponetes, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComponetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void txtEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUsuarioActionPerformed

    private void txtTelefoneUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneUsuarioActionPerformed

    private void rbtAtendimentoNormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAtendimentoNormaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtAtendimentoNormaActionPerformed

    private void cbmGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmGuicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmGuicheActionPerformed

    private void btnGerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarSenhaActionPerformed

    private void tblDadosTotais1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDadosTotais1AncestorAdded
        tblDadosTotais1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Diário", "0"},
                {"Semanal", "0"},
                {"Mensal", "0"},
                {"Anual", "0"}
            },
            new String [] {
                "Período", "Atendimentos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }//GEN-LAST:event_tblDadosTotais1AncestorAdded

    private void btnSairtelaAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairtelaAtendenteActionPerformed
        //new TelaLogin(clienteRepository, perfilRepository,usuarioRepository,usuarioService).setVisible(true);
       // this.dispose();
    }//GEN-LAST:event_btnSairtelaAtendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerarSenha;
    private javax.swing.JButton btnGerarsenhaPioritaria;
    private javax.swing.JButton btnSairtelaAtendente;
    private javax.swing.JComboBox<String> cbmGuiche;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAtendimentosPioridade1;
    private javax.swing.JLabel lblAtendimentosTotal1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblConfiguraçõesAtendimento;
    private javax.swing.JLabel lblCpfUsuario;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDescriação;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumerosAtendimentos;
    private javax.swing.JLabel lblOpcaoPioridade;
    private javax.swing.JLabel lblPainelAtendente1;
    private javax.swing.JLabel lblSenhasNormais1;
    private javax.swing.JLabel lblSenhasnaoPioritarias2;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTextoSuperior;
    private javax.swing.JLabel lblTotaldeAtendimentos;
    private javax.swing.JPanel pnlBairroUsuario;
    private javax.swing.JPanel pnlCidadeUsuario;
    private javax.swing.JPanel pnlComponetes;
    private javax.swing.JPanel pnlCpfUsuario;
    private javax.swing.JPanel pnlDataNascimento;
    private javax.swing.JPanel pnlDescricao;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlInformaçõesUsuario;
    private javax.swing.JPanel pnlMenuAtendente;
    private javax.swing.JPanel pnlNomeUsuario;
    private javax.swing.JPanel pnlNumeroResidencia;
    private javax.swing.JPanel pnlOpcoesAtendimento;
    private javax.swing.JPanel pnlSenhasnaoPioritarias2;
    private javax.swing.JPanel pnlTelefone;
    private javax.swing.JPanel pnlTotalPioridade;
    private javax.swing.JPanel pnlTotaldeAtendimentos;
    private javax.swing.JRadioButton rbtAtendimentoNorma;
    private javax.swing.JRadioButton rbtAtendimentoPioritario;
    private javax.swing.JTable tblDadosTotais1;
    private javax.swing.JTextField txtBairroUsuario;
    private javax.swing.JTextField txtCidadeUsuario;
    private javax.swing.JTextField txtCpfUsuario;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtNumeroResidencia;
    private javax.swing.JTextField txtTelefoneUsuario;
    private javax.swing.JLabel txtTotalPioridade;
    // End of variables declaration//GEN-END:variables
}
