/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.domain.Usuario;
import br.com.ifba.projetogerenciadorsenhas.repository.ClienteRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.PerfilRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.SenhaRepository;
import br.com.ifba.projetogerenciadorsenhas.repository.UsuarioRepository;
import br.com.ifba.projetogerenciadorsenhas.service.UsuarioService;
import javax.swing.JOptionPane;

/**
 *
 * @author fabricio
 */
    public class TelaLogin extends javax.swing.JFrame {
        private final ClienteRepository clienteRepository;
        private final PerfilRepository perfilRepository;
        private final UsuarioRepository usuarioRepository;
        private final UsuarioService usuarioService;
        private final SenhaRepository senhaRepository;


        public TelaLogin(ClienteRepository clienteRepository, PerfilRepository perfilRepository, UsuarioRepository usuarioRepository, UsuarioService usuarioService, SenhaRepository senhaRepository) {
            this.clienteRepository = clienteRepository;
            this.perfilRepository = perfilRepository;
            this.usuarioRepository = usuarioRepository;
            this.usuarioService = usuarioService;
            this.senhaRepository = senhaRepository;
            initComponents();
            setLocationRelativeTo(null);
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        private void realizarLogin() {
            
            String login = txtNomeUsuario.getText().trim();
            String senha = new String(pwdSenha.getPassword());

            try {
                Usuario usuario = usuarioService.logar(login, senha);
                System.out.println("usuarioService = " + usuarioService);
                System.out.println("=================================");
                System.out.println("Login digitado: " + login);
                System.out.println("ID Usuario: " + usuario.getId());
                System.out.println("Login Usuario: " + usuario.getLogin());
                System.out.println("Perfil Usuario: " + usuario.getPerfil().getNome());
                System.out.println("=================================");

                if (usuario != null){
                    String nomePerfil = usuario.getPerfil().getNome().toUpperCase().trim();

                    if (nomePerfil.contains("ADMINISTRADOR")){
                        new TelaAdministrador1(clienteRepository, perfilRepository, usuarioRepository, usuarioService).setVisible(true);

                    }else if(nomePerfil.contains("ATENDENTE")){
                        SenhaRepository senhaRepository = null;
                        new TelaAtendente1(clienteRepository, perfilRepository, usuarioService, senhaRepository).setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "Perfil não reconhecido: " + nomePerfil);
                    }
                        this.dispose();
                    }else{
                    JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!");
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Erro ao tentar realizar login: " + ex.getMessage());
                ex.printStackTrace(); 
            }
    }   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanoFundo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        pnlContainerUsuario = new javax.swing.JPanel();
        lblImagenUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        pnlContainerSenha = new javax.swing.JPanel();
        lblImagemSenha = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JPasswordField();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTextoInferior = new javax.swing.JLabel();
        lblProjct = new javax.swing.JLabel();
        lblTituloSuperior = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPanoFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlPanoFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        pnlPanoFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        pnlPanoFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 383, 350, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainerUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/UsuarioLogin24.png"))); // NOI18N

        txtNomeUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNomeUsuario.setText("Usuario");

        javax.swing.GroupLayout pnlContainerUsuarioLayout = new javax.swing.GroupLayout(pnlContainerUsuario);
        pnlContainerUsuario.setLayout(pnlContainerUsuarioLayout);
        pnlContainerUsuarioLayout.setHorizontalGroup(
            pnlContainerUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlContainerUsuarioLayout.setVerticalGroup(
            pnlContainerUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblImagenUsuario)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(pnlContainerUsuarioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtNomeUsuario)
                .addContainerGap())
        );

        jPanel1.add(pnlContainerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 50));

        pnlContainerSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        pnlContainerSenha.setForeground(new java.awt.Color(255, 0, 0));

        lblImagemSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/SenhaLogin.png"))); // NOI18N

        pwdSenha.setText("jPasswordField1");

        javax.swing.GroupLayout pnlContainerSenhaLayout = new javax.swing.GroupLayout(pnlContainerSenha);
        pnlContainerSenha.setLayout(pnlContainerSenhaLayout);
        pnlContainerSenhaLayout.setHorizontalGroup(
            pnlContainerSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagemSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlContainerSenhaLayout.setVerticalGroup(
            pnlContainerSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerSenhaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblImagemSenha)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(pnlContainerSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pwdSenha)
                .addContainerGap())
        );

        jPanel1.add(pnlContainerSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 300, 50));

        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblSenha.setText("Senha");
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblTextoInferior.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        lblTextoInferior.setText("Acesso de administradores e atendentes");
        jPanel1.add(lblTextoInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblProjct.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lblProjct.setForeground(new java.awt.Color(0, 153, 0));
        lblProjct.setText("Project");
        jPanel1.add(lblProjct, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        lblTituloSuperior.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        lblTituloSuperior.setText("Acessar Guichê");
        jPanel1.add(lblTituloSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(0, 153, 153));
        btnEntrar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, 60));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 10));

        pnlPanoFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanoFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanoFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        realizarLogin();
    }//GEN-LAST:event_btnEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblImagemSenha;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblProjct;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTextoInferior;
    private javax.swing.JLabel lblTituloSuperior;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlContainerSenha;
    private javax.swing.JPanel pnlContainerUsuario;
    private javax.swing.JPanel pnlPanoFundo;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
