/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

import br.com.ifba.projetogerenciadorsenhas.domain.Senha;
import javax.swing.JOptionPane;
import br.com.ifba.projetogerenciadorsenhas.repository.SenhaRepository;
import br.com.ifba.projetogerenciadorsenhas.service.SenhaService;
import org.springframework.beans.factory.annotation.Autowired;
import java.time.LocalDateTime;
import org.springframework.stereotype.Component;

/**
 *
 * @author fabricio
 */
@Component
public class TelaguicheFinaceiro extends javax.swing.JFrame {

    /**
     * Creates new form TelaguicheFinaceiro
     */
    private final SenhaService senhaService;
    private final SenhaRepository senhaRepository;


    public TelaguicheFinaceiro(SenhaService senhaService, SenhaRepository senhaRepository) {
        this.senhaService = senhaService;
        this.senhaRepository = senhaRepository;
        initComponents();
    }

    public TelaguicheFinaceiro() {
        this.senhaService = null;
        this.senhaRepository = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnlFundoGuiche = new javax.swing.JPanel();
        pnlMenuGuiche = new javax.swing.JPanel();
        lblPainelGuiche1 = new javax.swing.JLabel();
        lblSetor = new javax.swing.JLabel();
        lblNomecraturaSetor = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoAtendimento = new javax.swing.JTable();
        lblFilaSetor = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDadosTotais = new javax.swing.JTable();
        lblTabelaAtendimentos = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        cbsStatus = new javax.swing.JComboBox<>();
        lblTituPagina = new javax.swing.JLabel();
        pnlUsuarioAtual = new javax.swing.JPanel();
        lblUsuarioAtendido = new javax.swing.JLabel();
        btnChamaProximo = new javax.swing.JButton();
        btnRechamaProximo = new javax.swing.JButton();
        btnEncerraAtendimento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblProximasSenhas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabelaProximassenhas = new javax.swing.JTable();
        pnlTituloTabela = new javax.swing.JPanel();
        lblPosição = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblHoraChegada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundoGuiche.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundoGuiche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFundoGuiche.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuGuiche.setBackground(new java.awt.Color(0, 153, 153));
        pnlMenuGuiche.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPainelGuiche1.setBackground(new java.awt.Color(255, 255, 255));
        lblPainelGuiche1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblPainelGuiche1.setForeground(new java.awt.Color(255, 255, 255));
        lblPainelGuiche1.setText("Painel Guiche");
        pnlMenuGuiche.add(lblPainelGuiche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 15, -1, -1));

        lblSetor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblSetor.setForeground(new java.awt.Color(255, 255, 255));
        lblSetor.setText("Setor");
        pnlMenuGuiche.add(lblSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNomecraturaSetor.setForeground(new java.awt.Color(255, 255, 255));
        lblNomecraturaSetor.setText("FINANCEIRO E REGULAÇÃO FISCAL");
        pnlMenuGuiche.add(lblNomecraturaSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblStatus.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status");
        pnlMenuGuiche.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        pnlMenuGuiche.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 76, 310, 10));
        pnlMenuGuiche.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 300, 10));

        tblTipoAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Senha", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTipoAtendimento);

        pnlMenuGuiche.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 300, 190));

        lblFilaSetor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblFilaSetor.setForeground(new java.awt.Color(255, 255, 255));
        lblFilaSetor.setText("Fila Setor");
        pnlMenuGuiche.add(lblFilaSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        tblDadosTotais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Diario", "Semanal", "Mensal", "Anual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDadosTotais.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDadosTotaisAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tblDadosTotais);

        pnlMenuGuiche.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, 120));

        lblTabelaAtendimentos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTabelaAtendimentos.setForeground(new java.awt.Color(255, 255, 255));
        lblTabelaAtendimentos.setText("Atendimentos");
        pnlMenuGuiche.add(lblTabelaAtendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        pnlMenuGuiche.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 300, -1));

        cbsStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Em Atendimento", "Pausa", " " }));
        pnlMenuGuiche.add(cbsStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 174, 300, 30));

        pnlFundoGuiche.add(pnlMenuGuiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 340, 631));

        lblTituPagina.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTituPagina.setText("Módulo Atendimento - Controle de Chamadas");
        pnlFundoGuiche.add(lblTituPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 7, -1, -1));

        pnlUsuarioAtual.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuarioAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));

        lblUsuarioAtendido.setText("CLIENTE SENDO ATENDIDO");

        javax.swing.GroupLayout pnlUsuarioAtualLayout = new javax.swing.GroupLayout(pnlUsuarioAtual);
        pnlUsuarioAtual.setLayout(pnlUsuarioAtualLayout);
        pnlUsuarioAtualLayout.setHorizontalGroup(
            pnlUsuarioAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioAtualLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblUsuarioAtendido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUsuarioAtualLayout.setVerticalGroup(
            pnlUsuarioAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioAtualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioAtendido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFundoGuiche.add(pnlUsuarioAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 650, 190));

        btnChamaProximo.setBackground(new java.awt.Color(51, 204, 0));
        btnChamaProximo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnChamaProximo.setForeground(new java.awt.Color(255, 255, 255));
        btnChamaProximo.setText("Chamar Proximo");
        btnChamaProximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        btnChamaProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamaProximoActionPerformed(evt);
            }
        });
        pnlFundoGuiche.add(btnChamaProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 200, 50));

        btnRechamaProximo.setBackground(new java.awt.Color(204, 204, 0));
        btnRechamaProximo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnRechamaProximo.setForeground(new java.awt.Color(255, 255, 255));
        btnRechamaProximo.setText("Rechamar Proximo");
        btnRechamaProximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        pnlFundoGuiche.add(btnRechamaProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 200, 50));

        btnEncerraAtendimento.setBackground(new java.awt.Color(255, 51, 51));
        btnEncerraAtendimento.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnEncerraAtendimento.setForeground(new java.awt.Color(255, 255, 255));
        btnEncerraAtendimento.setText("Encerra");
        btnEncerraAtendimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pnlFundoGuiche.add(btnEncerraAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 200, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProximasSenhas.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblProximasSenhas.setText("Próximas Senhas Aguardando na Fila");
        jPanel2.add(lblProximasSenhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        tblTabelaProximassenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tblTabelaProximassenhas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 620, 142));

        pnlTituloTabela.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPosição.setText("Posição");

        lblSenha.setText("Senha");

        lblTipo.setText("Tipo");

        lblHoraChegada.setText("Hora Chegada");

        javax.swing.GroupLayout pnlTituloTabelaLayout = new javax.swing.GroupLayout(pnlTituloTabela);
        pnlTituloTabela.setLayout(pnlTituloTabelaLayout);
        pnlTituloTabelaLayout.setHorizontalGroup(
            pnlTituloTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTabelaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblPosição)
                .addGap(113, 113, 113)
                .addComponent(lblSenha)
                .addGap(109, 109, 109)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(lblHoraChegada)
                .addGap(32, 32, 32))
        );
        pnlTituloTabelaLayout.setVerticalGroup(
            pnlTituloTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosição)
                    .addComponent(lblSenha)
                    .addComponent(lblTipo)
                    .addComponent(lblHoraChegada))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(pnlTituloTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, 40));

        pnlFundoGuiche.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 650, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundoGuiche, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundoGuiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChamaProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamaProximoActionPerformed
        // Pega o guichê selecionado no combo box
        String guiche = cbsStatus.getSelectedItem().toString(); 

        // Chama o serviço
        Senha chamada = senhaService.chamarProximo(guiche);

        if (chamada != null) {
            JOptionPane.showMessageDialog(this, "Chamando senha: " + chamada.getCodigo());
            // Aqui você chamaria um método para atualizar a tabela
        } else {
            JOptionPane.showMessageDialog(this, "Fila vazia!");
        }
    }//GEN-LAST:event_btnChamaProximoActionPerformed

    private void tblDadosTotaisAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDadosTotaisAncestorAdded
        tblDadosTotais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Diário", "0"},
                {"Semanal", "0"},
                {"Mensal", "0"},
                {"Anual", "0"}
            },
            new String [] {
                "Período", "Atendimentos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }//GEN-LAST:event_tblDadosTotaisAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaguicheFinaceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaguicheFinaceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaguicheFinaceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaguicheFinaceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaguicheFinaceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamaProximo;
    private javax.swing.JButton btnEncerraAtendimento;
    private javax.swing.JButton btnRechamaProximo;
    private javax.swing.JComboBox<String> cbsStatus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFilaSetor;
    private javax.swing.JLabel lblHoraChegada;
    private javax.swing.JLabel lblNomecraturaSetor;
    private javax.swing.JLabel lblPainelGuiche1;
    private javax.swing.JLabel lblPosição;
    private javax.swing.JLabel lblProximasSenhas;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTabelaAtendimentos;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituPagina;
    private javax.swing.JLabel lblUsuarioAtendido;
    private javax.swing.JPanel pnlFundoGuiche;
    private javax.swing.JPanel pnlMenuGuiche;
    private javax.swing.JPanel pnlTituloTabela;
    private javax.swing.JPanel pnlUsuarioAtual;
    private javax.swing.JTable tblDadosTotais;
    private javax.swing.JTable tblTabelaProximassenhas;
    private javax.swing.JTable tblTipoAtendimento;
    // End of variables declaration//GEN-END:variables
}
