/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.projetogerenciadorsenhas.view;

/**
 *
 * @author fabricio
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundotela = new javax.swing.JPanel();
        pnlComponetes = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        pnlUsuario = new javax.swing.JPanel();
        lblUsuarioLogin24 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pnlSenha = new javax.swing.JPanel();
        lblSenhaLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        sptLinha = new javax.swing.JSeparator();
        btnEntra = new javax.swing.JButton();
        lblTituloSuperior = new javax.swing.JLabel();
        lblImagemLogotipo = new javax.swing.JLabel();
        lblLogotipoO = new javax.swing.JLabel();
        lblLogotipoO1 = new javax.swing.JLabel();
        lblProjct = new javax.swing.JLabel();
        lblTextoInferior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundotela.setBackground(new java.awt.Color(255, 255, 255));

        pnlComponetes.setBackground(new java.awt.Color(255, 255, 255));
        pnlComponetes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        pnlComponetes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setText("Usuário");
        pnlComponetes.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblSenha.setText("Senha");
        pnlComponetes.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        pnlUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        lblUsuarioLogin24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagems/UsuarioLogin24.png"))); // NOI18N

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioLogin24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioLogin24)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlComponetes.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 40));

        pnlSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        lblSenhaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagems/SenhaLogin.png"))); // NOI18N

        txtSenha.setForeground(new java.awt.Color(153, 153, 153));
        txtSenha.setText("Senha");
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSenhaLayout = new javax.swing.GroupLayout(pnlSenha);
        pnlSenha.setLayout(pnlSenhaLayout);
        pnlSenhaLayout.setHorizontalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSenhaLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSenhaLayout.setVerticalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaLogin)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlComponetes.add(pnlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 40));

        sptLinha.setBackground(new java.awt.Color(0, 102, 102));
        pnlComponetes.add(sptLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 10));

        btnEntra.setBackground(new java.awt.Color(0, 204, 204));
        btnEntra.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnEntra.setForeground(new java.awt.Color(255, 255, 255));
        btnEntra.setText("Entra");
        pnlComponetes.add(btnEntra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 150, 50));

        lblTituloSuperior.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        lblTituloSuperior.setText("Acessar Guichê");
        pnlComponetes.add(lblTituloSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lblImagemLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagems/logotipoP.png"))); // NOI18N
        pnlComponetes.add(lblImagemLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 60, -1));

        lblLogotipoO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagems/LogotipoO.png"))); // NOI18N
        pnlComponetes.add(lblLogotipoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 40));

        lblLogotipoO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagems/LogotipoO.png"))); // NOI18N
        pnlComponetes.add(lblLogotipoO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 40, 40));

        lblProjct.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblProjct.setForeground(new java.awt.Color(0, 153, 0));
        lblProjct.setText("Projct");
        pnlComponetes.add(lblProjct, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        lblTextoInferior.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        lblTextoInferior.setText("Acesso de adiministradores e atendentes");
        pnlComponetes.add(lblTextoInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        javax.swing.GroupLayout pnlFundotelaLayout = new javax.swing.GroupLayout(pnlFundotela);
        pnlFundotela.setLayout(pnlFundotelaLayout);
        pnlFundotelaLayout.setHorizontalGroup(
            pnlFundotelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundotelaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlComponetes, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlFundotelaLayout.setVerticalGroup(
            pnlFundotelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundotelaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlComponetes, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundotela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundotela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntra;
    private javax.swing.JLabel lblImagemLogotipo;
    private javax.swing.JLabel lblLogotipoO;
    private javax.swing.JLabel lblLogotipoO1;
    private javax.swing.JLabel lblProjct;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaLogin;
    private javax.swing.JLabel lblTextoInferior;
    private javax.swing.JLabel lblTituloSuperior;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioLogin24;
    private javax.swing.JPanel pnlComponetes;
    private javax.swing.JPanel pnlFundotela;
    private javax.swing.JPanel pnlSenha;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JSeparator sptLinha;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
